/*
 * VistaGlobal.java
 *
 * Created on 23-nov-2009, 11:03:25
 */

package vista;


import vista.cliente.ClienteView;
import javax.swing.JPanel;
import vista.factura.FacturaView;


/**
 *
 * @author Norberto Díaz-Díaz
 */
public class VistaGlobal extends javax.swing.JFrame /*implements ClienteView*/{
    private ClienteView clienteView;
    private FacturaView facturaView;

    /** Creates new form VistaGlobal */
    public VistaGlobal(ClienteView clienteView, FacturaView facturaView) {
        this.clienteView=clienteView;
        this.facturaView=facturaView;
        initComponents();
        this.jTabbedPanel.add("Cliente",(JPanel)clienteView);
        this.jTabbedPanel.add("Factura", (JPanel)facturaView);
        this.setTitle("Aplicación de Facturación");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPanelMouseClicked
       if(this.jTabbedPanel.getSelectedIndex()==1)
        facturaView.display();
    }//GEN-LAST:event_jTabbedPanelMouseClicked

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPanel;
    // End of variables declaration//GEN-END:variables


 
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                clienteView.display();
                //facturaView.display();
            }
        });
        
    }
}
